# Generated by Django 5.1.4 on 2024-12-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="department_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="specialty",
            name="Specialty_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
