# Generated by Django 5.1.3 on 2024-12-09 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.IntegerField(
                        choices=[
                            (1, "第一节"),
                            (2, "第二节"),
                            (3, "第三节"),
                            (4, "第四节"),
                            (5, "第五节"),
                        ],
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="specialty",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="course",
            name="credits",
        ),
        migrations.RemoveField(
            model_name="course",
            name="department",
        ),
        migrations.RemoveField(
            model_name="department",
            name="description",
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="exam",
            name="exam_type",
            field=models.CharField(
                choices=[("midterm", "期中"), ("final", "期末")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="score",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="retakeexam",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retake_exams",
                to="api.enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="retakeexam",
            name="new_score",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="retakeexam",
            name="original_exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retake_exams",
                to="api.exam",
            ),
        ),
        migrations.AlterField(
            model_name="rewardpunishment",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="rewardpunishment",
            name="type",
            field=models.CharField(
                choices=[("reward", "奖励"), ("punishment", "惩罚")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.department",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(choices=[("M", "男"), ("F", "女")], max_length=10),
        ),
        migrations.AlterField(
            model_name="student",
            name="id_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.specialty",
            ),
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(max_length=50)),
                ("teacher", models.CharField(max_length=100)),
                ("capacity", models.PositiveIntegerField(default=30)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="api.course",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.timeslot"
                    ),
                ),
            ],
            options={
                "unique_together": {("group", "time_slot")},
            },
        ),
        migrations.RemoveField(
            model_name="specialty",
            name="description",
        ),
        migrations.CreateModel(
            name="CourseSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.class"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_selections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "class_instance")},
            },
        ),
    ]
