# Generated by Django 5.1.4 on 2024-12-17 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_student_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseinstance",
            name="day",
        ),
        migrations.RemoveField(
            model_name="courseinstance",
            name="period",
        ),
    ]
