# Generated by Django 5.1.4 on 2024-12-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_department_department_id_specialty_specialty_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
