# Generated by Django 5.1.4 on 2024-12-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_courseschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseprototype",
            name="credits",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
