# Generated by Django 5.1.4 on 2024-12-17 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_courseprototype_credits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseinstance",
            name="eligible_departments",
        ),
        migrations.RemoveField(
            model_name="courseinstance",
            name="eligible_grades",
        ),
        migrations.AlterField(
            model_name="courseinstance",
            name="eligible_classes",
            field=models.ManyToManyField(
                default=None, related_name="eligible_course_instances", to="api.class"
            ),
        ),
        migrations.AlterField(
            model_name="courseinstance",
            name="selected_students",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="course_selected_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
