# Generated by Django 5.1.4 on 2024-12-18 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_courseinstance_daily_weight_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="api.department",
            ),
        ),
        migrations.AddField(
            model_name="courseinstance",
            name="eligible_departments",
            field=models.ManyToManyField(
                related_name="eligible_course_instances", to="api.department"
            ),
        ),
        migrations.AddField(
            model_name="courseinstance",
            name="eligible_grades",
            field=models.ManyToManyField(
                related_name="eligible_course_instances", to="api.grade"
            ),
        ),
        migrations.AddField(
            model_name="courseinstance",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_instances",
                to="api.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="courseinstance",
            name="selected_students",
            field=models.ManyToManyField(
                blank=True, related_name="selected_courses", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
