# Generated by Django 5.1.4 on 2024-12-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_class_department_courseinstance_eligible_departments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseinstance",
            name="is_grades_published",
            field=models.BooleanField(default=False),
        ),
    ]
