# Generated by Django 5.1.4 on 2024-12-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_courseinstance_is_grades_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="s_grade",
            name="daily_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="s_grade",
            name="final_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="s_grade",
            name="total_score",
            field=models.FloatField(default=0.0),
        ),
    ]
