# Generated by Django 5.1.4 on 2024-12-21 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_s_grade_daily_score_alter_s_grade_final_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("selection_start_week", models.PositiveIntegerField(default=1)),
                ("selection_end_week", models.PositiveIntegerField(default=2)),
                ("current_week", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="PunishmentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DISCIPLINE", "纪律处分"),
                            ("ACADEMIC", "学术处分"),
                            ("OTHER", "其他"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="punishments",
                        to="api.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RewardRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("EXCELLENCE", "优秀学生"), ("OTHER", "其他")],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="api.student",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="courseinstance",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_instances",
                to="api.semester",
            ),
        ),
    ]
