# Generated by Django 5.1.4 on 2024-12-22 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_student_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelectionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("start_selection_date", models.DateTimeField()),
                ("end_selection_date", models.DateTimeField()),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selection_batches",
                        to="api.semester",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="courseinstance",
            name="selection_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_instances",
                to="api.selectionbatch",
            ),
        ),
    ]
