# Generated by Django 5.1.4 on 2024-12-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_selectionbatch_courseinstance_selection_batch"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseschedule",
            options={
                "verbose_name": "课程时间安排",
                "verbose_name_plural": "课程时间安排",
            },
        ),
        migrations.AlterUniqueTogether(
            name="courseschedule",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="courseschedule",
            name="end_week",
            field=models.PositiveIntegerField(default=1, help_text="课程结束的周数"),
        ),
        migrations.AddField(
            model_name="courseschedule",
            name="exceptions",
            field=models.JSONField(
                blank=True, default=list, help_text="例外周数，课程在这些周不进行"
            ),
        ),
        migrations.AddField(
            model_name="courseschedule",
            name="frequency",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="上课频率（如1表示每周一次，2表示每两周一次）"
            ),
        ),
        migrations.AddField(
            model_name="courseschedule",
            name="start_week",
            field=models.PositiveIntegerField(default=1, help_text="课程开始的周数"),
        ),
        migrations.AlterUniqueTogether(
            name="courseschedule",
            unique_together={
                ("course_instance", "day", "period", "start_week", "frequency")
            },
        ),
    ]
