# Generated by Django 5.1.4 on 2024-12-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_courseschedule_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="total_weeks",
            field=models.PositiveIntegerField(default=20, help_text="学期总周数"),
        ),
    ]
