# Generated by Django 5.1.4 on 2024-12-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_semester_total_weeks"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
    ]
