# Generated by Django 5.1.4 on 2024-12-23 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_semester_is_current"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="s_grade",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="s_grade",
            name="attempt",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "首考"), (2, "补考"), (3, "重修")],
                default=1,
                verbose_name="考试轮次",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="s_grade",
            unique_together={("student", "course_instance", "attempt")},
        ),
    ]
