# Generated by Django 5.1.3 on 2024-12-07 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(default="null", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(default="null", max_length=10),
        ),
        migrations.AlterField(
            model_name="student",
            name="major",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
