# Generated by Django 5.1.3 on 2024-12-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="number",
            field=models.CharField(max_length=40, verbose_name="number"),
        ),
    ]
