# Generated by Django 5.1.3 on 2024-12-02 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0006_rename_roles_role"),
        ("DataManager", "0002_alter_classroom_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "related_auth_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Auth.authuser"
                    ),
                ),
            ],
        ),
    ]
