# Generated by Django 5.1.3 on 2024-12-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0004_student_department_student_grade_student_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=40, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name",
            field=models.CharField(max_length=40, null=True, verbose_name="name"),
        ),
    ]
