# Generated by Django 5.1.3 on 2024-12-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0008_alter_timeslot_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="slot",
            field=models.CharField(
                choices=[
                    ("0", "8:00-10:00"),
                    ("1", "10:10-12:00"),
                    ("2", "14:00-15:50"),
                    ("3", "16:10-18:00"),
                    ("4", "19:00-20:50"),
                ],
                max_length=8,
                unique=True,
                unique_for_date=False,
                verbose_name="slot",
            ),
        ),
    ]
