# Generated by Django 5.1.3 on 2024-12-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0010_alter_timeslot_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="brithday",
            field=models.DateField(null=True, verbose_name="birthday"),
        ),
        migrations.AddField(
            model_name="student",
            name="identity_id",
            field=models.CharField(
                default=111111111111, max_length=20, verbose_name="identity_id"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="sex",
            field=models.CharField(
                choices=[("0", "Male"), ("1", "Female")],
                default=0,
                max_length=10,
                verbose_name="sex",
            ),
            preserve_default=False,
        ),
    ]
