# Generated by Django 5.1.3 on 2024-12-03 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0011_student_brithday_student_identity_id_student_sex"),
    ]

    operations = [
        migrations.CreateModel(
            name="Punish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="name")),
                ("detail", models.CharField(max_length=200, verbose_name="detail")),
            ],
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="name")),
                ("detail", models.CharField(max_length=200, verbose_name="detail")),
            ],
        ),
        migrations.CreateModel(
            name="StudentPunish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "punish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataManager.punish",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataManager.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="punishes",
            field=models.ManyToManyField(
                through="DataManager.StudentPunish", to="DataManager.punish"
            ),
        ),
        migrations.CreateModel(
            name="StudentReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataManager.reward",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataManager.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="rewards",
            field=models.ManyToManyField(
                through="DataManager.StudentReward", to="DataManager.reward"
            ),
        ),
    ]
