# Generated by Django 5.1.3 on 2024-12-03 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0013_major_student_major"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Punish",
            new_name="Punishment",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="punishes",
            new_name="punishments",
        ),
    ]
