# Generated by Django 5.1.3 on 2024-12-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0014_rename_punish_punishment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="week",
            field=models.IntegerField(null=True, verbose_name="week"),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="day",
            field=models.IntegerField(null=True, verbose_name="day"),
        ),
    ]
