# Generated by Django 5.1.3 on 2024-12-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0015_timeslot_week_alter_timeslot_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="teacher_id",
            field=models.CharField(max_length=40, null=True, verbose_name="teacher_id"),
        ),
    ]
