# Generated by Django 5.1.3 on 2024-12-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0019_teacher_permissioned_departments"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="permissioned_majors",
            field=models.ManyToManyField(
                related_name="permissioned_majors",
                through="DataManager.MajorPermission",
                to="DataManager.major",
            ),
        ),
    ]
