# Generated by Django 5.1.3 on 2024-12-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0020_teacher_permissioned_majors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                max_length=40, null=True, unique=True, verbose_name="student_id"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="teacher_id",
            field=models.CharField(
                max_length=40, null=True, unique=True, verbose_name="teacher_id"
            ),
        ),
    ]
