# Generated by Django 5.1.3 on 2024-12-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0021_alter_student_student_id_alter_teacher_teacher_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="punishment",
            name="time",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="reward",
            name="time",
            field=models.DateField(null=True),
        ),
    ]
