# Generated by Django 5.1.3 on 2024-12-04 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0022_punishment_time_reward_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataManager.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Selection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="name")),
                (
                    "courses",
                    models.ManyToManyField(
                        through="DataManager.CourseSelection", to="DataManager.course"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="courseselection",
            name="selection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataManager.selection"
            ),
        ),
    ]
