# Generated by Django 5.1.3 on 2024-12-04 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0023_courseselection_selection_courseselection_selection"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseselection",
            name="capacity",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="courseselection",
            name="num",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="selection",
            name="end_date",
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 8, 0)),
        ),
        migrations.AddField(
            model_name="selection",
            name="start_date",
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 8, 0)),
        ),
    ]
