# Generated by Django 5.1.3 on 2024-12-04 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0024_courseselection_capacity_courseselection_num_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataManager.section",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataManager.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentSelectionCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataManager.course",
                    ),
                ),
                (
                    "studentselection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataManager.studentselection",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentselection",
            name="selected_courses",
            field=models.ManyToManyField(
                through="DataManager.StudentSelectionCourse", to="DataManager.course"
            ),
        ),
    ]
