# Generated by Django 5.1.3 on 2024-12-04 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0025_studentselection_studentselectioncourse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentselection",
            name="selection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataManager.selection"
            ),
        ),
    ]
