# Generated by Django 5.1.3 on 2024-12-04 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0026_alter_studentselection_selection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selection",
            name="end_date",
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 8, 0)),
        ),
        migrations.AlterField(
            model_name="selection",
            name="start_date",
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 8, 0)),
        ),
    ]
