# Generated by Django 5.1.3 on 2024-12-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0027_alter_selection_end_date_alter_selection_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="section",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
