# Generated by Django 5.1.3 on 2024-12-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataManager", "0028_alter_section_end_date_alter_section_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentselection",
            name="checked",
            field=models.BooleanField(default=False),
        ),
    ]
