# Generated by Django 5.1.3 on 2024-11-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, verbose_name="username")),
                ("pwd_md5", models.CharField(max_length=20, verbose_name="pwd_md5")),
            ],
        ),
    ]
