# Generated by Django 5.1.3 on 2024-11-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authuser",
            name="salt",
            field=models.CharField(max_length=20, null=True, verbose_name="salt"),
        ),
    ]
