# Generated by Django 5.1.3 on 2024-11-30 06:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0002_authuser_salt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authuser",
            name="salt",
        ),
    ]
