# Generated by Django 5.1.3 on 2024-12-02 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0004_alter_authuser_pwd_md5_alter_authuser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_name",
                    models.CharField(max_length=40, verbose_name="role_name"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="authuser",
            name="role",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="Auth.roles"
            ),
        ),
    ]
